<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       DB::table('activities')->insert([
            [
                'id' => 1,
                'user_id' => 17,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pengelolaan Kebun',
                'activity_budget' => 317040000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pengadaan Pakaian Kerja',
                'activity_budget' => 206869000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pembayaran Terkait Pelaksanaan Operasional Perkantoran',
                'activity_budget' => 86544000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Layanan Daya dan Jasa',
                'activity_budget' => 767304000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pemeliharaan Kantor',
                'activity_budget' => 2372947000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Kebutuhan Sehari-hari Perkantoran',
                'activity_budget' => 1706336000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'user_id' => 16,
                'work_group_id' => 4,
                'work_team_id' => 9,
                'status_id' => 1,
                'name' => 'Pembayaran Gaji dan Tunjangan',
                'activity_budget' => 8699616000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'user_id' => 16,
                'work_group_id' => 4,
                'work_team_id' => 9,
                'status_id' => 1,
                'name' => 'Pembinaan Administrasi Pengelolaan Keuangan dan SAP',
                'activity_budget' => 33400000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'user_id' => 14,
                'work_group_id' => 4,
                'work_team_id' => 7,
                'status_id' => 1,
                'name' => 'Pembinaan Administrasi/ Pengelolaan Kepegawaian dan SDM',
                'activity_budget' => 56520000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pengelolaan Ketatausahaan dan Kearsipan',
                'activity_budget' => 39081000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'user_id' => 15,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'status_id' => 1,
                'name' => 'Pengelolaan Administrasi Perlengkapan dan Inventarisasi Asset/BMN',
                'activity_budget' => 10000000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'user_id' => 12,
                'work_group_id' => 3,
                'work_team_id' => 5,
                'status_id' => 1,
                'name' => 'Pengelolaan PNBP Laboratorium Pengujian dan Sertifikasi Alsintan',
                'activity_budget' => 2369206000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'user_id' => 13,
                'work_group_id' => 3,
                'work_team_id' => 6,
                'status_id' => 1,
                'name' => 'Akreditasi Laboratorium Pengujian',
                'activity_budget' => 36124000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'user_id' => 10,
                'work_group_id' => 2,
                'work_team_id' => 3,
                'status_id' => 1,
                'name' => 'Pengelolaan Instrumen Hasil Standardisasi dan Pengujian Mekanisasi Pertanian',
                'activity_budget' => 24695000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'user_id' => 11,
                'work_group_id' => 2,
                'work_team_id' => 4,
                'status_id' => 1,
                'name' => 'Pengembangan Teknologi Informasi, Perpustakaan Digital dan Pengelolaan Pelayanan PubliK',
                'activity_budget' => 33110000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'user_id' => 18,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'status_id' => 1,
                'name' => 'Pendampingan Program Strategis Kementerian Pertanian',
                'activity_budget' => 1135000000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'user_id' => 9,
                'work_group_id' => 1,
                'work_team_id' => 2,
                'status_id' => 1,
                'name' => 'Pengelolaan Program Perakitan dan Perekayasaan Mekanisasi Pertanian',
                'activity_budget' => 12700000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'user_id' => 18,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'status_id' => 1,
                'name' => 'Pembinaan dan Koordinasi Kegiatan Pengujian Standar Instrumen Mekanisasi Pertanian',
                'activity_budget' => 18010000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'user_id' => 2,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'status_id' => 1,
                'name' => 'Sistem Pengendalian Intern dan Manajemen Resiko Indeks',
                'activity_budget' => 7680000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'user_id' => 2,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'status_id' => 1,
                'name' => 'Monitoring, Evaluasi dan Unit Pengelola Gratifikasi',
                'activity_budget' => 31815000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'user_id' => 8,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'status_id' => 1,
                'name' => 'Penyusunan Program dan Anggaran',
                'activity_budget' => 56865000,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
