<?php

namespace Database\Seeders;

use App\Models\Activity;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonthlyActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $activities = Activity::all();

        $activity = \App\Models\Activity::first(); 

        $data = [
            [
                'id' => 1,
                'activity_id' => 1,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 17,
                'updated_by' => 17,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:51:09',
            ],
            [
                'id' => 2,
                'activity_id' => 2,
                'financial_target' => null,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-14 13:28:17',
            ],
            [
                'id' => 3,
                'activity_id' => 3,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:54:26',
            ],
            [
                'id' => 4,
                'activity_id' => 4,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:54:05',
            ],
            [
                'id' => 5,
                'activity_id' => 5,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:53:41',
            ],
            [
                'id' => 6,
                'activity_id' => 6,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:53:20',
            ],
            [
                'id' => 7,
                'activity_id' => 7,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 16,
                'updated_by' => 16,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:52:57',
            ],
            [
                'id' => 8,
                'activity_id' => 8,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 16,
                'updated_by' => 16,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:52:24',
            ],
            [
                'id' => 9,
                'activity_id' => 9,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 14,
                'updated_by' => 14,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:51:59',
            ],
            [
                'id' => 10,
                'activity_id' => 10,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:51:33',
            ],
            [
                'id' => 11,
                'activity_id' => 11,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 15,
                'updated_by' => 15,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:45:43',
            ],
            [
                'id' => 12,
                'activity_id' => 12,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 12,
                'updated_by' => 12,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:50:45',
            ],
            [
                'id' => 13,
                'activity_id' => 13,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 13,
                'updated_by' => 13,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:50:16',
            ],
            [
                'id' => 14,
                'activity_id' => 14,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 10,
                'updated_by' => 10,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:49:51',
            ],
            [
                'id' => 15,
                'activity_id' => 15,
                'financial_target' => null,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 11,
                'updated_by' => 11,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-14 13:28:17',
            ],
            [
                'id' => 16,
                'activity_id' => 16,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 18,
                'updated_by' => 18,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:49:23',
            ],
            [
                'id' => 17,
                'activity_id' => 17,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 9,
                'updated_by' => 9,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:49:00',
            ],
            [
                'id' => 18,
                'activity_id' => 18,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 18,
                'updated_by' => 18,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:48:40',
            ],
            [
                'id' => 19,
                'activity_id' => 19,
                'financial_target' => null,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-14 13:28:17',
            ],
            [
                'id' => 20,
                'activity_id' => 20,
                'financial_target' => null,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-14 13:28:17',
            ],
            [
                'id' => 21,
                'activity_id' => 21,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2025-09-14 13:28:17',
                'updated_at' => '2025-09-15 06:47:48',
            ],
            [
                'id' => 22,
                'activity_id' => 11,
                'financial_target' => 0.00,
                'financial_realization' => 4839500.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:27:42',
                'updated_at' => '2025-09-15 06:27:42',
            ],
            [
                'id' => 23,
                'activity_id' => 21,
                'financial_target' => 0.00,
                'financial_realization' => 37708692.00,
                'physical_target' => 0.00,
                'physical_realization' => 75.00,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Revisi ke-10 Angaran TA 2025"]),
                'issues' => json_encode(["Optimalisasi belanja pegawai yang digunakan masih menggunakan data perkiraan realisasi dan realisasi anggaran yang sudah dibuka blokirnya tidak sesuai dengan rencana pernarikan anggranan"]),
                'follow_ups' => json_encode(["Melakukan monitoring realisasi setiap bulan"]),
                'planned_tasks' => json_encode(["Melakukan revisi pergeseran anggaran jika terjadi pagu minus belanja pegawai dan melaksanakan kegiatan sesuai dengan rencana penarikan dana anggaran yang sudah dibuat"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:30:20',
                'updated_at' => '2025-09-15 07:06:20',
            ],
            [
                'id' => 24,
                'activity_id' => 20,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => 0.00,
                'physical_realization' => 65.00,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Update data dan/atau monitoring aplikasi e-Monev BSIP, e-Monev Bappenas, e-Sakip, SMART", "Kompilasi data laporan progres kegiatan dari setiap bidang sebagai bahan laporan bulanan", "Penyusunan laporan Bulanan, Dumas, Gratifikasi, KRO-RO, dan Renaksi", "Pengumpulan Evidence untuk evaluasi mandiri pembangun ZI tahun 2025", "Penyusunan Laporan bulanan renaksi SPI KPK"]),
                'issues' => json_encode(["Aplikasi e-Monev BSIP & E-Sakip (belum bisa diakses)"]),
                'follow_ups' => json_encode(["Koordinasi dengan BRMP dan menunggu aplikasi bisa diakses"]),
                'planned_tasks' => json_encode(["Update data dan/atau monitoring aplikasi e-Monev BSIP, e-Monev Bappenas, e-Sakip, SMART", "Rapat bulanan BRMP Mektan", "Kompilasi data laporan progres kegiatan dari setiap bidang sebagai bahan laporan bulanan", "Penyusunan laporan Bulanan, Dumas, Gratifikasi, KRO-RO, dan Renaksi", "Internalisasi Hasil Identifikasi Matrik Benting 2025", "Pengumpulan Evidence untuk evaluasi mandiri pembangun ZI tahun 2025", "Penyusunan Laporan bulanan renaksi SPI KPK"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:30:52',
                'updated_at' => '2025-09-15 06:44:57',
            ],
            [
                'id' => 25,
                'activity_id' => 19,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:31:12',
                'updated_at' => '2025-09-15 07:09:45',
            ],
            [
                'id' => 26,
                'activity_id' => 18,
                'financial_target' => 0.00,
                'financial_realization' => 17055000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:31:51',
                'updated_at' => '2025-09-15 06:31:51',
            ],
            [
                'id' => 27,
                'activity_id' => 17,
                'financial_target' => 0.00,
                'financial_realization' => 4975000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:32:28',
                'updated_at' => '2025-09-15 06:32:28',
            ],
            [
                'id' => 28,
                'activity_id' => 16,
                'financial_target' => 0.00,
                'financial_realization' => 326284795.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 06:35:35',
                'updated_at' => '2025-09-15 06:35:35',
            ],
            [
                'id' => 29,
                'activity_id' => 15,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 07:08:39',
                'updated_at' => '2025-09-15 07:08:39',
            ],
            [
                'id' => 30,
                'activity_id' => 14,
                'financial_target' => 0.00,
                'financial_realization' => 15631500.00,
                'physical_target' => 70.00,
                'physical_realization' => 70.00,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Layanan kegiatan magang, penelitian, PKL mahasiswa", "Pelaksanaan kegiatan peningkatan kapasitas petani terkait pengoperasian, perawatan dan perbaikan TR2, TR4, dan Combine harvester", "Laporan kerjasama TW2 lingkup BRMP", "Pembahasan kegiatan kerjasama dengan S-BIN", "Pengusulan perbaikan CNC melalui kegiatan TASK (korea)", "Penandatanganan PKS dengan PT. ECHA", "Pemantauan kegiatan hibah CSAM dan penandatanganan amandemen LoA hibah CSAM", "Pembahasan kegiatan kerjasama dengan UICI"]),
                'issues' => json_encode([null, "Lahan untuk latihan terbatas", "PAGU perjalanan dinas kegiatan Hibah masih diusulkan untuk dapat direkonsilisasi", "Masih dalam tahap penyusunan proposal, membutuhkan data teknis kebutuhan kegiatan", "Dengan adanya perubahan tusi mektan, perawatan CNC kurang memadai dan mengalami kerusakan", "PT. ECHA ingin meminjam peralatan pabrikasi milik Mektan", "Belum adanya akun DIPA sehingga kegiatan belum seluruhnya dapat di SPJkan dan adanya perubahan nama institusi sehingga penandatanganan terhambat", "Masih dalam tahap pembahasan"]),
                'follow_ups' => json_encode([null, "Dilakukan di lahan petani sekitar Mektan, dan combine harvester hanya disampaikan materinya saja", "Menunggu hasil rekonsilisasi dan mencari pagu alternatif lainnya", "Dilakukan meeting dari berbagai satker dan mengundang para praktisi", "Korea membuka program perbaikan peralatan permesinan melalui kegiatan TASK, Mektan mencoba mengusulkan", "Masih dalam tahap pertimbangan, PKS dilakukan hanya untuk uji kinerja alsintan", "Akan dibuat matrik anggaran untuk pembentukan Akun oleh bag. Program dan telah meminta sekretariat untuk menginformasikan nama satker versi english", "Perlu adanya dukungan dari berbagai satker"]),
                'planned_tasks' => json_encode(["Kegiatan layanan penelitian, magang dan PKL mahasiswa", "Monitoring kegiatan hibah CSAM", "Layanan kunjungan, kerjasama, dll", "Permohonan pemutakhiran data hibah", "Kegiatan peningkatan kapasitas petani Kutai Barat"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 07:31:28',
                'updated_at' => '2025-09-15 07:31:28',
            ],
            [
                'id' => 31,
                'activity_id' => 13,
                'financial_target' => 0.00,
                'financial_realization' => 1500000.00,
                'physical_target' => 39.00,
                'physical_realization' => 7.00,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Perbaikan dokumen Sistem Mutu Laboratorium", "Pembelian ATK dan keperluan komputer"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode(["Perbaikan dokumen Sistem Mutu Laboratorium", "Fotokopi, pencetakan dan penggandaan dokumen Sistem Mutu Laboratorium"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 07:46:34',
                'updated_at' => '2025-09-15 08:13:33',
            ],
            [
                'id' => 32,
                'activity_id' => 12,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => 0.00,
                'physical_realization' => 0.00,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Menerima permohonan pengujian yang diajukan pemohon uji sampai dengan bulan Agustus 2025 sebanyak 437 permohonan uji yang belum diselesaikan", "Menerima kunjungan dari laboratorium CREATA IPB dalam rangka studi banding pengujian pompa air irigasi di BRMP Mektan pada 14 Agustus 2025", "Melaksanakan koordinasi rencana perluasan 19 ruang lingkup LSPro dan persiapan assesmen KAN", "Mempersiapan MoU dengan penambahan 1 auditor eksternal", "Mempersiapkan rencana peningkatan kompetensi personil", "Mengikuti Sosialisasi Kebijakan Ketentuan Pembayaran Iuran Tahunan bagi LPK yang diakreditasi Komite Akreditasi Nasional (KAN U-09) dan koordinasi kegiatan akreditasi LPK", "Melaksanakan PPC dan audit lapang/kesesuaian untuk PT. KHS dan PT. Pura Barutama"]),
                'issues' => json_encode(["Layanan pengujian alsintan dan layanan sertifikasi belum bisa dilaksanakan secara reguler karena anggaran operasional masih diblokir"]),
                'follow_ups' => json_encode(["Melakukan pengujian alsintan dengan bantuan pembiayaan dari Ditjen PSP", "Melaksanakan kegiatan menggunakan anggaran kegiatan kemitraan dalam proses layanan sertifikasi (LSPro)"]),
                'planned_tasks' => json_encode(["Menunggu buka blokir anggaran PNBP", "Melaksanakan Audit Internal LSPro", "Melaksanakan kegiatan peningkatan kompetensi personil LSPro", "Melanjutkan persiapan dokumen untuk perluasan ruang lingkup dan survei KAN"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 07:57:55',
                'updated_at' => '2025-09-15 07:57:55',
            ],
            [
                'id' => 33,
                'activity_id' => 9,
                'financial_target' => 0.00,
                'financial_realization' => 17703600.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:02:18',
                'updated_at' => '2025-09-15 08:02:18',
            ],
            [
                'id' => 34,
                'activity_id' => 8,
                'financial_target' => 0.00,
                'financial_realization' => 15819000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Mengirimkan perbaikan proposal PNBP 73%, KAK PNBP untuk pengajuan Ijin Penggunaan PNBP ke sekretariat BRMP", "Mengirimkan revisi Belanja Pegawai dan Penyesuaian Rincian Output, file pdf data rincian pembayaran gaji PPPK Tahap I dan CPNS ke sekretariat BRMP"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:12:22',
                'updated_at' => '2025-09-15 08:12:22',
            ],
            [
                'id' => 35,
                'activity_id' => 7,
                'financial_target' => 0.00,
                'financial_realization' => 5865302386.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Pembuatan Gaji Induk Pegawai dan PPPK bulan September 2025", "Pembuatan uang makan Bulan Juli 2025", "Pembuatan Kekurangan Gaji yang mengalami kenaikan Gaji Berkala", "Pembuatan Billing tagihan pengembalian tunjangan suami meninggal atas nama pegawai Mulyani"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode(["Pembuatan Gaji Induk Pegawai dan PPPK bulan Oktober 2025", "Pembuatan uang makan Bulan Agustus 2025"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:16:16',
                'updated_at' => '2025-09-15 08:16:16',
            ],
            [
                'id' => 36,
                'activity_id' => 1,
                'financial_target' => 0.00,
                'financial_realization' => 227200000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:48:12',
                'updated_at' => '2025-09-15 08:48:12',
            ],
            [
                'id' => 37,
                'activity_id' => 10,
                'financial_target' => 0.00,
                'financial_realization' => 19821000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:48:56',
                'updated_at' => '2025-09-15 08:48:56',
            ],
            [
                'id' => 38,
                'activity_id' => 6,
                'financial_target' => 0.00,
                'financial_realization' => 1022699000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:49:47',
                'updated_at' => '2025-09-15 08:49:47',
            ],
            [
                'id' => 39,
                'activity_id' => 5,
                'financial_target' => 0.00,
                'financial_realization' => 1635361340.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:50:25',
                'updated_at' => '2025-09-15 08:50:25',
            ],
            [
                'id' => 40,
                'activity_id' => 4,
                'financial_target' => 0.00,
                'financial_realization' => 417088835.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 08:53:39',
                'updated_at' => '2025-09-15 08:53:39',
            ],
            [
                'id' => 41,
                'activity_id' => 3,
                'financial_target' => 0.00,
                'financial_realization' => 50672000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 09:01:54',
                'updated_at' => '2025-09-15 09:01:54',
            ],
            [
                'id' => 42,
                'activity_id' => 2,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 8, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-15 09:02:35',
                'updated_at' => '2025-09-15 09:02:35',
            ],
            [
                'id' => 43,
                'activity_id' => 21,
                'financial_target' => 0.00,
                'financial_realization' => 26365998.00,
                'physical_target' => 0.00,
                'physical_realization' => 65.00,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Revisi ke-9 Anggaran TA 2025"]),
                'issues' => json_encode(["Nilai IKPA BBRM Mektan sampai dengan bulan juni sebesar 88,63 (sudah mendekati batas minimal dalam perjanjian kinerja sebesar 87)"]),
                'follow_ups' => json_encode(["Melakukan revisi Rencana Penarikan Dana (RPD)"]),
                'planned_tasks' => json_encode(["Melaksanakan kegiatan sesuai dengan rencana penarikan dana anggaran yang sudah dibuat"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:45:59',
                'updated_at' => '2025-09-16 00:45:59',
            ],
            [
                'id' => 44,
                'activity_id' => 20,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => 0.00,
                'physical_realization' => 60.00,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Update data dan/atau monitoring aplikasi e-Monev BSIP, e-Monev Bappenas, e-Sakip, SMART", "Rapat bulanan BRMP Mektan", "Kompilasi data laporan progres kegiatan dari setiap bidang sebagai bahan laporan bulanan", "Penyusunan laporan Bulanan, Dumas, Gratifikasi, KRO-RO, dan Renaksi", "Pengumpulan Evidence untuk evaluasi mandiri pembangun ZI tahun 2025", "Evaluasi mandiri dan monev triwulan 2 pembangunan ZI 2025", "Evaluasi mandiri SPIP maturitas 2025", "Penyusunan Laporan bulanan renaksi SPI KPK", "Workshop capaian kinerja triwulan 2 2025"]),
                'issues' => json_encode(["Aplikasi e-Monev BSIP (belum bisa diakses)"]),
                'follow_ups' => json_encode(["Koordinasi dengan BSIP dan menunggu aplikasi bisa diakses"]),
                'planned_tasks' => json_encode(["Update data dan/atau monitoring aplikasi e-Monev BSIP, e-Monev Bappenas, e-Sakip, SMART", "Rapat bulanan BRMP Mektan", "Kompilasi data laporan progres kegiatan dari setiap bidang sebagai bahan laporan bulanan", "Penyusunan laporan Bulanan, Dumas, Gratifikasi, KRO-RO, dan Renaksi", "Internalisasi Hasil Identifikasi Matrik Benting 2025", "Pengumpulan Evidence untuk evaluasi mandiri pembangun ZI tahun 2025", "Pengumpulan evidence untuk evaluasi mandiri SPIP maturitas 2025"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:54:03',
                'updated_at' => '2025-09-16 00:54:03',
            ],
            [
                'id' => 45,
                'activity_id' => 19,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:54:44',
                'updated_at' => '2025-09-16 00:54:44',
            ],
            [
                'id' => 46,
                'activity_id' => 18,
                'financial_target' => 0.00,
                'financial_realization' => 17055000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:55:26',
                'updated_at' => '2025-09-16 00:55:26',
            ],
            [
                'id' => 47,
                'activity_id' => 17,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:55:54',
                'updated_at' => '2025-09-16 00:55:54',
            ],
            [
                'id' => 48,
                'activity_id' => 16,
                'financial_target' => 0.00,
                'financial_realization' => 209710045.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Koordinasi dengan koordinator penyuluh pertanian untuk mendorong pelaksanaan percepatan tanam dan mensinkronkan data realisasi tanam", "Koordinasi dengan BBWS terkait ketersediaan air di lahan irigasi teknis untuk MT-III", "Realisasi tanam padi pada bulan Juli di Kabupaten Lampung Tengah sebesar 5.089 ha"]),
                'issues' => json_encode(["Sebagian petani ragu melaksanakan tanam pada MT-III dikarenakan tidak adanya kepastian ketersediaan air di lahan dan adanya informasi terkait penutupan pintu air akibat dari perbaikan irigasi"]),
                'follow_ups' => json_encode(["Melakukan koordinasi dengan BBWS untuk menjamin ketersediaan air selama MT-III khususnya di daerah irigasi teknis", "Melakukan konfirmasi kepada BBWS terkait ada atau tidaknya penutupan pintu air akibat dari perbaikan irigasi, hasilnya tidak ada penutupan pintu air, meskipun ada normalisasi irigasi air tetap akan dialirkan"]),
                'planned_tasks' => json_encode(["Rapat Koordinasi LTT seluruh Kabupaten di Provinsi Lampung untuk menentukan target kesanggupan masing-masing Kabupaten untuk tanam bulan Agustus", "Koordinasi dengan koordinator penyuluh seluruh kecamatan di Kabupaten Lampung Tengah untuk menetapkan target dan kesanggupan tanam di bulan Agustus, mensinkronkan data realisasi tanam, serta mendorong pelaksanaan percepatan tanam"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:56:36',
                'updated_at' => '2025-09-16 01:03:03',
            ],
            [
                'id' => 49,
                'activity_id' => 15,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 00:58:38',
                'updated_at' => '2025-09-16 00:58:38',
            ],
            [
                'id' => 50,
                'activity_id' => 14,
                'financial_target' => 0.00,
                'financial_realization' => 9665500.00,
                'physical_target' => 60.00,
                'physical_realization' => 60.00,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Layanan kegiatan magang, penelitian, PKL mahasiswa (40 orang)", "Pelaksanaan kegiatan capacity building penyusunan SOP Drone Sprayer", "Pembuatan draft laporan tengah tahun", "Pembahasan kegiatan kerjasama dengan S-BIN dan KRRI", "Pembahasan kerjasama dengan BRIN", "Penandatanganan PKS dengan Ilsang", "Pemantauan kegiatan hibah CSAM", "Pembahasan rencana hibah dari pemerintah RRT melalui FAO terkait pertanian modern", "Laporan kegiatan hibah ke Biro KLN"]),
                'issues' => json_encode(["Tidak adanya support pendanaan bagi mahasiswa magang, penelitian dan PKL", "Tidak adanya anggaran di Mektan", "-", "Masih dalam tahap penyusunan proposal, membutuhkan data teknis kebutuhan kegiatan", "Adanya overlap tusi", "-", "Belum adanya akun DIPA, sehingga kegiatan belum seluruhnya dapat di-SPJ-kan"]),
                'follow_ups' => json_encode(["Mahasiswa magang dan PKL mengikuti kegiatan teknis yang ada, untuk mahasiswa penelitian pendanaan mandiri", "Pendanaan kegiatan dari Croplife Indonesia sesuai dengan perjanjian kerja sama", "-", "Dilakukan meeting dari berbagai satker dan mengundang para praktisi", "Dilakukan kesepakatan perbedaan tusi dengan menghadirkan Kementan, DJA, Bappenas dan BRIN", "-", "Akan dibuat matrik anggaran untuk pembentukan Akun oleh bag. Program"]),
                'planned_tasks' => json_encode(["Kegiatan layanan penelitian, magang dan PKL mahasiswa", "Monitoring kegiatan hibah CSAM", "Layanan kunjungan, kerjasama, dll"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:20:33',
                'updated_at' => '2025-09-16 01:20:33',
            ],
            [
                'id' => 51,
                'activity_id' => 13,
                'financial_target' => 0.00,
                'financial_realization' => 1500000.00,
                'physical_target' => 26.00,
                'physical_realization' => 5.00,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Perbaikan dokumen Sistem Mutu Laboratorium", "Audit Internal Laboratorium", "Pembelian ATK dan keperluan komputer"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode(["Perbaikan dokumen Sistem Mutu Laboratorium"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:26:45',
                'updated_at' => '2025-09-16 01:26:45',
            ],
            [
                'id' => 52,
                'activity_id' => 12,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Menerima permohonan pengujian yang diajukan pemohon uji sampai dengan bulan Juli 2025 sudah diterima 429 permohonan uji yang belum diselesaikan", "Menyusun perbaikan data usulan persetujuan penggunaan PNBP dan usulan pengadaan alat laboratorium dengan anggaran ICARE", "Mengirimkan 12 surat konfirmasi kepada perusahaan terkait status permohonan sertifikasi yang masih menggunakan nama LSPro BBPSI Mektan", "Menerima kunjungan dari Polda Kaltim terkait dengan permintaan keterangan produk pertanian dan penggunaan tanda SNI pada produk Rice Processing Unit (RPU)", "Mengajukan surat permohonan penundaan jadwal survei ke KAN yang semula dijadwalkan pada September 2025 menjadi Desember terkait dengan rencana perluasan ruang lingkup LSPro", "Mengikuti rapat harmonisasi atas 6 Rancangan Peratauran Badan Standardisasi Nasional (RPBSN) bersama Kemenhum, BSN, dan LSPro terdampak", "Mengikuti FGD Penambahan Persyaratan pada E-katalog Sektoral Terkait Pengambilan Sampel Alsintan untuk Test Report dan FGD Pengalihan LSPro Alsintan Ditjen PSP ke BRMP"]),
                'issues' => json_encode(["Layanan pengujian dan sertifikasi alsintan belum bisa dilaksanakan secara reguler karena anggaran operasional yang masih diblokir"]),
                'follow_ups' => json_encode(["Melakukan pengujian alsintan dengan bantuan pembiayaan dari Ditjen PSP", "Melaksanakan kegiatan non teknis yang paralel bisa dimulai sementara menunggu anggaran operasional", "Melaksanakan kegiatan menggunakan anggaran kegiatan kemitraan dalam proses layanan sertifikasi (LSPro)"]),
                'planned_tasks' => json_encode(["Menunggu buka blokir anggaran PNBP", "Melakukan pengujian pompa air irigasi, germinator dan sprayer dengan dukungan pembiayaan pengujian Ditjen PSP", "Mempersiapkan audit untuk PT. KHS dan PT. Pura", "Mempersiapkan kelengkapan doksistu untuk rencana perluasan ruang lingkup LSPro"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:34:07',
                'updated_at' => '2025-09-16 01:34:07',
            ],
            [
                'id' => 53,
                'activity_id' => 9,
                'financial_target' => 0.00,
                'financial_realization' => 14438600.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:41:45',
                'updated_at' => '2025-09-16 01:41:45',
            ],
            [
                'id' => 54,
                'activity_id' => 8,
                'financial_target' => 0.00,
                'financial_realization' => 12727000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Melaksanakan Workshop Verifikasi dan Reviu Laporan Keuangan/BMN Semester I TA 2025 UAPPA/B E-1 di Bogor", "Mengikuti Zoom dari BRM terkait Konfirmasi Belanja Pegawai Tahun 2025", "Mengirimkan Proposal PNBP 73%, KAK PNBP untuk pengajuan Ijin Penggunaan PNBP ke sekretariat BRMP"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:44:14',
                'updated_at' => '2025-09-16 01:44:14',
            ],
            [
                'id' => 55,
                'activity_id' => 7,
                'financial_target' => 0.00,
                'financial_realization' => 5261906585.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode(["Pembuatan Gaji Induk ASN dan PPPK bulan Agustus 2025", "Pembuatan uang makan ASN dan PPPK bulan Juni 2025", "Pembuatan Gaji Susulan Bulan Juni untuk 5 pegawai CPNS"]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode(["Pembuatan Gaji Induk Pegawai dan PPPK bulan September 2025", "Pembuatan uang makan Bulan Juli 2025", "Pembuatan Kekurangan Gaji yang mengalami kenaikan Gaji Berkala", "Pembuatan Billing tagihan pengembalian tunjangan suami meninggal atas nama pegawai Mulyani"]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:48:31',
                'updated_at' => '2025-09-16 01:48:31',
            ],
            [
                'id' => 56,
                'activity_id' => 11,
                'financial_target' => 0.00,
                'financial_realization' => 4839500.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:49:23',
                'updated_at' => '2025-09-16 01:49:23',
            ],
            [
                'id' => 57,
                'activity_id' => 6,
                'financial_target' => 0.00,
                'financial_realization' => 854367950.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:50:00',
                'updated_at' => '2025-09-16 01:50:00',
            ],
            [
                'id' => 58,
                'activity_id' => 5,
                'financial_target' => 0.00,
                'financial_realization' => 1283307829.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:51:03',
                'updated_at' => '2025-09-16 01:51:03',
            ],
            [
                'id' => 59,
                'activity_id' => 4,
                'financial_target' => 0.00,
                'financial_realization' => 357798883.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:51:49',
                'updated_at' => '2025-09-16 01:51:49',
            ],
            [
                'id' => 60,
                'activity_id' => 3,
                'financial_target' => 0.00,
                'financial_realization' => 44040000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:52:30',
                'updated_at' => '2025-09-16 01:52:30',
            ],
            [
                'id' => 61,
                'activity_id' => 1,
                'financial_target' => 0.00,
                'financial_realization' => 205120000.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:53:21',
                'updated_at' => '2025-09-16 01:53:21',
            ],
            [
                'id' => 62,
                'activity_id' => 10,
                'financial_target' => 0.00,
                'financial_realization' => 13076300.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:54:15',
                'updated_at' => '2025-09-16 01:54:15',
            ],
            [
                'id' => 63,
                'activity_id' => 2,
                'financial_target' => 0.00,
                'financial_realization' => 0.00,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(2025, 7, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => json_encode([null]),
                'issues' => json_encode([null]),
                'follow_ups' => json_encode([null]),
                'planned_tasks' => json_encode([null]),
                'created_by' => $activity->user_id,
                'updated_by' => $activity->user_id,
                'created_at' => '2025-09-16 01:55:25',
                'updated_at' => '2025-09-16 01:55:25',
            ],
        ];

        DB::table('monthly_activities')->insert($data);

    }
}

