<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonthlyActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('monthly_activities')->insert([
            [
                'id' => 1,
                'activity_id' => 1,
                'financial_target' => null,
                'financial_realization' => 227200000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'activity_id' => 2,
                'financial_target' => null,
                'financial_realization' => 0,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'activity_id' => 3,
                'financial_target' => null,
                'financial_realization' => 50672000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'activity_id' => 4,
                'financial_target' => null,
                'financial_realization' => 417088835,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'activity_id' => 5,
                'financial_target' => null,
                'financial_realization' => 1635361340,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'activity_id' => 6,
                'financial_target' => null,
                'financial_realization' => 1022699600,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'activity_id' => 7,
                'financial_target' => null,
                'financial_realization' => 5865302386,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'activity_id' => 8,
                'financial_target' => null,
                'financial_realization' => 15819000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'activity_id' => 9,
                'financial_target' => null,
                'financial_realization' => 17703600,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'activity_id' => 10,
                'financial_target' => null,
                'financial_realization' => 19821000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'activity_id' => 11,
                'financial_target' => null,
                'financial_realization' => 4839500,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'activity_id' => 12,
                'financial_target' => null,
                'financial_realization' => 0,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'activity_id' => 13,
                'financial_target' => null,
                'financial_realization' => 1500000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'activity_id' => 14,
                'financial_target' => null,
                'financial_realization' => 15631500,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'activity_id' => 15,
                'financial_target' => null,
                'financial_realization' => 0,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'activity_id' => 16,
                'financial_target' => null,
                'financial_realization' => 326284795,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'activity_id' => 17,
                'financial_target' => null,
                'financial_realization' => 4975000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'activity_id' => 18,
                'financial_target' => null,
                'financial_realization' => 17055000,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'activity_id' => 19,
                'financial_target' => null,
                'financial_realization' => 0,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'activity_id' => 20,
                'financial_target' => null,
                'financial_realization' => 0,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'activity_id' => 21,
                'financial_target' => null,
                'financial_realization' => 37708692,
                'physical_target' => null,
                'physical_realization' => null,
                'period' => Carbon::create(now('Asia/Jakarta')->year, 9, 1, 0, 0, 0, 'Asia/Jakarta'),
                'completed_tasks' => null,
                'issues' => null,
                'follow_ups' => null,
                'planned_tasks' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
