<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'role_id' => 1,
                'work_group_id' => 2,
                'work_team_id' => 4,
                'name' => 'Muhammad Rizky',
                'email' => 'rizky@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'role_id' => 2,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'name' => 'Sri Utami',
                'email' => 'utami@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'role_id' => 2,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'name' => 'Meriska',
                'email' => 'meriska.yulia@pertanian.go.id',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'role_id' => 2,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'name' => 'Harsono',
                'email' => 'Harsono@gmail',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'role_id' => 3,
                'work_group_id' => 2,
                'work_team_id' => 4,
                'name' => 'Sulha Pangaribu',
                'email' => 'sulha@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'role_id' => 3,
                'work_group_id' => 5,
                'work_team_id' => 3,
                'name' => 'Muhammad Iqbal',
                'email' => 'm.iqbal@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'role_id' => 3,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'name' => 'Suphendi',
                'email' => 'suphendi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'role_id' => 3,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'name' => 'Fero',
                'email' => 'fero@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'role_id' => 3,
                'work_group_id' => 1,
                'work_team_id' => 2,
                'name' => 'Amiq Nurul Azmi',
                'email' => 'amiq@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'role_id' => 3,
                'work_group_id' => 2,
                'work_team_id' => 3,
                'name' => 'Daragantina Nursani',
                'email' => 'dara.n@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'role_id' => 3,
                'work_group_id' => 2,
                'work_team_id' => 4,
                'name' => 'Tri Saksono',
                'email' => 'tri.s@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'role_id' => 3,
                'work_group_id' => 3,
                'work_team_id' => 5,
                'name' => 'Rudi Hermawan',
                'email' => 'rudi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'role_id' => 3,
                'work_group_id' => 3,
                'work_team_id' => 6,
                'name' => 'Ivony Hari',
                'email' => 'ivony@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'role_id' => 3,
                'work_group_id' => 4,
                'work_team_id' => 7,
                'name' => 'Titin Nuryawati',
                'email' => 'titin@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'role_id' => 3,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'name' => 'Kartini',
                'email' => 'kartini@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'role_id' => 3,
                'work_group_id' => 4,
                'work_team_id' => 9,
                'name' => 'Sigid Hadiwibowo',
                'email' => 'sigid@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'role_id' => 3,
                'work_group_id' => 4,
                'work_team_id' => 8,
                'name' => 'Faiyun',
                'email' => 'faiyun@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'role_id' => 3,
                'work_group_id' => 1,
                'work_team_id' => 1,
                'name' => 'Agung Prabowo',
                'email' => 'agung.p@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
